---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample-api-sfs
spec:
  serviceName: sample-api-svc
  replicas: 2
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      volumes:
        - name: nfs-volume
          nfs:
            server: nfs-server.default.svc.cluster.local
            path: "/"
            readOnly: false
      containers:
      - name: sample-api
        image: gcr.io/miani-gcloud/pvc-sample-api
        ports:
        - containerPort: 5000
          name: web
        volumeMounts:
        - name: nfs-volume
          mountPath: /app/data
